name: Upload Python Package

#on: # only triggered on manuel release creation
#  release:
#    types: [published]

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:

  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      # useless to create prerelease for each dev version but usefull to push to pypi

      # - name: Create prerelease
      #  if: contains( github.ref_name, 'dev' ) && startsWith( github.ref_name, 'v')
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    tag: ${{ github.ref_name }}
      #  run: |
      #    gh release create "$tag" \
      #       --repo="$GITHUB_REPOSITORY" \
      #       --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
      #       --generate-notes \
      #       --prerelease

      - name: Create release
        if: (false == contains( github.ref_name, 'dev' )) && startsWith( github.ref_name, 'v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
             --repo="$GITHUB_REPOSITORY" \
             --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
             --generate-notes \